# Study queue — 768 problems

Generated by `lc-queue-build.py`. Order is prerequisite-first: each
problem sits under the most advanced technique it needs, so nothing
arrives before the idea behind it. Within a unit: easy first, and
most-asked first inside each difficulty.


## Arrays & Hashing

1. [Two Sum](https://leetcode.com/problems/two-sum) — Easy
2. [Shuffle the Array](https://leetcode.com/problems/shuffle-the-array) — Easy
3. [Find All Numbers Disappeared in an Array](https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array) — Easy
4. [Max Consecutive Ones](https://leetcode.com/problems/max-consecutive-ones) — Easy
5. [Check if Array Is Sorted and Rotated](https://leetcode.com/problems/check-if-array-is-sorted-and-rotated) — Easy
6. [Trionic Array I](https://leetcode.com/problems/trionic-array-i) — Easy
7. [Unique Number of Occurrences](https://leetcode.com/problems/unique-number-of-occurrences) — Easy
8. [N-Repeated Element in Size 2N Array](https://leetcode.com/problems/n-repeated-element-in-size-2n-array) — Easy
9. [Summary Ranges](https://leetcode.com/problems/summary-ranges) — Easy
10. [Valid Mountain Array](https://leetcode.com/problems/valid-mountain-array) — Easy
11. [Find Common Elements Between Two Arrays](https://leetcode.com/problems/find-common-elements-between-two-arrays) — Easy
12. [Find Indices of Stable Mountains](https://leetcode.com/problems/find-indices-of-stable-mountains) — Easy
13. [Max Pair Sum in an Array](https://leetcode.com/problems/max-pair-sum-in-an-array) — Easy
14. [Insert Interval](https://leetcode.com/problems/insert-interval) — Medium
15. [Brick Wall](https://leetcode.com/problems/brick-wall) — Medium
16. [Count Special Triplets](https://leetcode.com/problems/count-special-triplets) — Medium
17. [Minimum Distance Between Three Equal Elements II](https://leetcode.com/problems/minimum-distance-between-three-equal-elements-ii) — Medium
18. [First Missing Positive](https://leetcode.com/problems/first-missing-positive) — Hard

## Strings

19. [Length of Last Word](https://leetcode.com/problems/length-of-last-word) — Easy
20. [Isomorphic Strings](https://leetcode.com/problems/isomorphic-strings) — Easy
21. [Ransom Note](https://leetcode.com/problems/ransom-note) — Easy
22. [Rotate String](https://leetcode.com/problems/rotate-string) — Easy
23. [Repeated Substring Pattern](https://leetcode.com/problems/repeated-substring-pattern) — Easy
24. [Check if Strings Can be Made Equal With Operations I](https://leetcode.com/problems/check-if-strings-can-be-made-equal-with-operations-i) — Easy
25. [Find Words That Can Be Formed by Characters](https://leetcode.com/problems/find-words-that-can-be-formed-by-characters) — Easy
26. [Score of a String](https://leetcode.com/problems/score-of-a-string) — Easy
27. [Check if Binary String Has at Most One Segment of Ones](https://leetcode.com/problems/check-if-binary-string-has-at-most-one-segment-of-ones) — Easy
28. [Check if the Sentence Is Pangram](https://leetcode.com/problems/check-if-the-sentence-is-pangram) — Easy
29. [Count Residue Prefixes](https://leetcode.com/problems/count-residue-prefixes) — Easy
30. [Count Vowel Substrings of a String](https://leetcode.com/problems/count-vowel-substrings-of-a-string) — Easy
31. [Find Common Characters](https://leetcode.com/problems/find-common-characters) — Easy
32. [Find Most Frequent Vowel and Consonant](https://leetcode.com/problems/find-most-frequent-vowel-and-consonant) — Easy
33. [Find Words Containing Character](https://leetcode.com/problems/find-words-containing-character) — Easy
34. [Furthest Point From Origin](https://leetcode.com/problems/furthest-point-from-origin) — Easy
35. [Jewels and Stones](https://leetcode.com/problems/jewels-and-stones) — Easy
36. [Maximum Number of Balloons](https://leetcode.com/problems/maximum-number-of-balloons) — Easy
37. [Number of Lines To Write String](https://leetcode.com/problems/number-of-lines-to-write-string) — Easy
38. [Remove Letter To Equalize Frequency](https://leetcode.com/problems/remove-letter-to-equalize-frequency) — Easy
39. [Shuffle String](https://leetcode.com/problems/shuffle-string) — Easy
40. [Verifying an Alien Dictionary](https://leetcode.com/problems/verifying-an-alien-dictionary) — Easy
41. [Word Pattern](https://leetcode.com/problems/word-pattern) — Easy
42. [String to Integer (atoi)](https://leetcode.com/problems/string-to-integer-atoi) — Medium
43. [Zigzag Conversion](https://leetcode.com/problems/zigzag-conversion) — Medium
44. [Count the Number of Special Characters II](https://leetcode.com/problems/count-the-number-of-special-characters-ii) — Medium
45. [Group Shifted Strings](https://leetcode.com/problems/group-shifted-strings) — Medium
46. [Count and Say](https://leetcode.com/problems/count-and-say) — Medium
47. [Subdomain Visit Count](https://leetcode.com/problems/subdomain-visit-count) — Medium
48. [Sum of Beauty of All Substrings](https://leetcode.com/problems/sum-of-beauty-of-all-substrings) — Medium
49. [Find and Replace Pattern](https://leetcode.com/problems/find-and-replace-pattern) — Medium
50. [Validate IP Address](https://leetcode.com/problems/validate-ip-address) — Medium
51. [Shortest Palindrome](https://leetcode.com/problems/shortest-palindrome) — Hard

## Two Pointers

52. [Remove Duplicates from Sorted Array](https://leetcode.com/problems/remove-duplicates-from-sorted-array) — Easy
53. [Merge Strings Alternately](https://leetcode.com/problems/merge-strings-alternately) — Easy
54. [Move Zeroes](https://leetcode.com/problems/move-zeroes) — Easy
55. [Remove Element](https://leetcode.com/problems/remove-element) — Easy
56. [Valid Palindrome](https://leetcode.com/problems/valid-palindrome) — Easy
57. [Find the Index of the First Occurrence in a String](https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string) — Easy
58. [Reverse String](https://leetcode.com/problems/reverse-string) — Easy
59. [Reverse Vowels of a String](https://leetcode.com/problems/reverse-vowels-of-a-string) — Easy
60. [Reverse String II](https://leetcode.com/problems/reverse-string-ii) — Easy
61. [Count Binary Substrings](https://leetcode.com/problems/count-binary-substrings) — Easy
62. [Next Permutation](https://leetcode.com/problems/next-permutation) — Medium
63. [Reverse Words in a String](https://leetcode.com/problems/reverse-words-in-a-string) — Medium
64. [Swap Adjacent in LR String](https://leetcode.com/problems/swap-adjacent-in-lr-string) — Medium
65. [Remove Duplicates from Sorted Array II](https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii) — Medium
66. [Move Pieces to Obtain a String](https://leetcode.com/problems/move-pieces-to-obtain-a-string) — Medium
67. [String Compression](https://leetcode.com/problems/string-compression) — Medium

## Sliding Window

68. [Maximum Average Subarray I](https://leetcode.com/problems/maximum-average-subarray-i) — Easy
69. [Contains Duplicate II](https://leetcode.com/problems/contains-duplicate-ii) — Easy
70. [Longest Substring Without Repeating Characters](https://leetcode.com/problems/longest-substring-without-repeating-characters) — Medium
71. [Longest Repeating Character Replacement](https://leetcode.com/problems/longest-repeating-character-replacement) — Medium
72. [Fruit Into Baskets](https://leetcode.com/problems/fruit-into-baskets) — Medium
73. [Permutation in String](https://leetcode.com/problems/permutation-in-string) — Medium
74. [Find All Anagrams in a String](https://leetcode.com/problems/find-all-anagrams-in-a-string) — Medium
75. [Number of Substrings Containing All Three Characters](https://leetcode.com/problems/number-of-substrings-containing-all-three-characters) — Medium
76. [Maximum Sum of Distinct Subarrays With Length K](https://leetcode.com/problems/maximum-sum-of-distinct-subarrays-with-length-k) — Medium
77. [Maximum Erasure Value](https://leetcode.com/problems/maximum-erasure-value) — Medium
78. [Minimum Window Substring](https://leetcode.com/problems/minimum-window-substring) — Hard
79. [Subarrays with K Different Integers](https://leetcode.com/problems/subarrays-with-k-different-integers) — Hard
80. [Substring with Concatenation of All Words](https://leetcode.com/problems/substring-with-concatenation-of-all-words) — Hard

## Prefix Sum

81. [Running Sum of 1d Array](https://leetcode.com/problems/running-sum-of-1d-array) — Easy
82. [Find the Highest Altitude](https://leetcode.com/problems/find-the-highest-altitude) — Easy
83. [Left and Right Sum Differences](https://leetcode.com/problems/left-and-right-sum-differences) — Easy
84. [Find Pivot Index](https://leetcode.com/problems/find-pivot-index) — Easy
85. [Minimum Value to Get Positive Step by Step Sum](https://leetcode.com/problems/minimum-value-to-get-positive-step-by-step-sum) — Easy
86. [Subarray Sum Equals K](https://leetcode.com/problems/subarray-sum-equals-k) — Medium
87. [Product of Array Except Self](https://leetcode.com/problems/product-of-array-except-self) — Medium
88. [Binary Subarrays With Sum](https://leetcode.com/problems/binary-subarrays-with-sum) — Medium
89. [Subarray Sums Divisible by K](https://leetcode.com/problems/subarray-sums-divisible-by-k) — Medium
90. [Maximum Good Subarray Sum](https://leetcode.com/problems/maximum-good-subarray-sum) — Medium
91. [Contiguous Array](https://leetcode.com/problems/contiguous-array) — Medium
92. [Corporate Flight Bookings](https://leetcode.com/problems/corporate-flight-bookings) — Medium
93. [Longest Balanced Substring II](https://leetcode.com/problems/longest-balanced-substring-ii) — Medium
94. [Maximum Points You Can Obtain from Cards](https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards) — Medium
95. [Minimum Moves to Make Array Complementary](https://leetcode.com/problems/minimum-moves-to-make-array-complementary) — Medium
96. [Make Sum Divisible by P](https://leetcode.com/problems/make-sum-divisible-by-p) — Medium
97. [Sum of Distances](https://leetcode.com/problems/sum-of-distances) — Medium

## Sorting

98. [Merge Sorted Array](https://leetcode.com/problems/merge-sorted-array) — Easy
99. [Valid Anagram](https://leetcode.com/problems/valid-anagram) — Easy
100. [Can Make Arithmetic Progression From Sequence](https://leetcode.com/problems/can-make-arithmetic-progression-from-sequence) — Easy
101. [Contains Duplicate](https://leetcode.com/problems/contains-duplicate) — Easy
102. [Squares of a Sorted Array](https://leetcode.com/problems/squares-of-a-sorted-array) — Easy
103. [Third Maximum Number](https://leetcode.com/problems/third-maximum-number) — Easy
104. [Check if Array is Good](https://leetcode.com/problems/check-if-array-is-good) — Easy
105. [Minimum Absolute Difference](https://leetcode.com/problems/minimum-absolute-difference) — Easy
106. [Find Missing Elements](https://leetcode.com/problems/find-missing-elements) — Easy
107. [Sort Array By Parity](https://leetcode.com/problems/sort-array-by-parity) — Easy
108. [Longest Harmonious Subsequence](https://leetcode.com/problems/longest-harmonious-subsequence) — Easy
109. [Minimum Difference Between Highest and Lowest of K Scores](https://leetcode.com/problems/minimum-difference-between-highest-and-lowest-of-k-scores) — Easy
110. [Sorting the Sentence](https://leetcode.com/problems/sorting-the-sentence) — Easy
111. [Widest Vertical Area Between Two Points Containing No Points](https://leetcode.com/problems/widest-vertical-area-between-two-points-containing-no-points) — Easy
112. [3Sum](https://leetcode.com/problems/3sum) — Medium
113. [Merge Intervals](https://leetcode.com/problems/merge-intervals) — Medium
114. [Group Anagrams](https://leetcode.com/problems/group-anagrams) — Medium
115. [4Sum](https://leetcode.com/problems/4sum) — Medium
116. [Sort Colors](https://leetcode.com/problems/sort-colors) — Medium
117. [3Sum Closest](https://leetcode.com/problems/3sum-closest) — Medium
118. [Find All Duplicates in an Array](https://leetcode.com/problems/find-all-duplicates-in-an-array) — Medium
119. [Find And Replace in String](https://leetcode.com/problems/find-and-replace-in-string) — Medium
120. [Majority Element II](https://leetcode.com/problems/majority-element-ii) — Medium
121. [Check if Strings Can be Made Equal With Operations II](https://leetcode.com/problems/check-if-strings-can-be-made-equal-with-operations-ii) — Medium
122. [H-Index](https://leetcode.com/problems/h-index) — Medium
123. [Invalid Transactions](https://leetcode.com/problems/invalid-transactions) — Medium
124. [Determine if Two Strings Are Close](https://leetcode.com/problems/determine-if-two-strings-are-close) — Medium
125. [Find Players With Zero or One Losses](https://leetcode.com/problems/find-players-with-zero-or-one-losses) — Medium
126. [Maximize Area of Square Hole in Grid](https://leetcode.com/problems/maximize-area-of-square-hole-in-grid) — Medium
127. [Maximum Gap](https://leetcode.com/problems/maximum-gap) — Medium
128. [Meeting Scheduler](https://leetcode.com/problems/meeting-scheduler) — Medium

## Binary Search

129. [Intersection of Two Arrays](https://leetcode.com/problems/intersection-of-two-arrays) — Easy
130. [Binary Search](https://leetcode.com/problems/binary-search) — Easy
131. [Search Insert Position](https://leetcode.com/problems/search-insert-position) — Easy
132. [Kth Missing Positive Number](https://leetcode.com/problems/kth-missing-positive-number) — Easy
133. [Intersection of Two Arrays II](https://leetcode.com/problems/intersection-of-two-arrays-ii) — Easy
134. [Minimum Common Value](https://leetcode.com/problems/minimum-common-value) — Easy
135. [Find Target Indices After Sorting Array](https://leetcode.com/problems/find-target-indices-after-sorting-array) — Easy
136. [Koko Eating Bananas](https://leetcode.com/problems/koko-eating-bananas) — Medium
137. [Search in Rotated Sorted Array](https://leetcode.com/problems/search-in-rotated-sorted-array) — Medium
138. [Two Sum II - Input Array Is Sorted](https://leetcode.com/problems/two-sum-ii-input-array-is-sorted) — Medium
139. [Single Element in a Sorted Array](https://leetcode.com/problems/single-element-in-a-sorted-array) — Medium
140. [Find First and Last Position of Element in Sorted Array](https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array) — Medium
141. [Find Peak Element](https://leetcode.com/problems/find-peak-element) — Medium
142. [Max Consecutive Ones III](https://leetcode.com/problems/max-consecutive-ones-iii) — Medium
143. [Minimum Size Subarray Sum](https://leetcode.com/problems/minimum-size-subarray-sum) — Medium
144. [Capacity To Ship Packages Within D Days](https://leetcode.com/problems/capacity-to-ship-packages-within-d-days) — Medium
145. [Search in Rotated Sorted Array II](https://leetcode.com/problems/search-in-rotated-sorted-array-ii) — Medium
146. [Separate Squares I](https://leetcode.com/problems/separate-squares-i) — Medium
147. [Find Minimum in Rotated Sorted Array](https://leetcode.com/problems/find-minimum-in-rotated-sorted-array) — Medium
148. [Find the Smallest Divisor Given a Threshold](https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold) — Medium
149. [Minimum Number of Days to Make m Bouquets](https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets) — Medium
150. [Minimum Removals to Balance Array](https://leetcode.com/problems/minimum-removals-to-balance-array) — Medium
151. [Peak Index in a Mountain Array](https://leetcode.com/problems/peak-index-in-a-mountain-array) — Medium
152. [Subarray Product Less Than K](https://leetcode.com/problems/subarray-product-less-than-k) — Medium
153. [K-diff Pairs in an Array](https://leetcode.com/problems/k-diff-pairs-in-an-array) — Medium
154. [Minimum Operations to Reduce X to Zero](https://leetcode.com/problems/minimum-operations-to-reduce-x-to-zero) — Medium
155. [Closest Equal Element Queries](https://leetcode.com/problems/closest-equal-element-queries) — Medium
156. [Maximum Distance Between a Pair of Values](https://leetcode.com/problems/maximum-distance-between-a-pair-of-values) — Medium
157. [Zero Array Transformation II](https://leetcode.com/problems/zero-array-transformation-ii) — Medium
158. [Find Minimum in Rotated Sorted Array II](https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii) — Hard

## Matrix

159. [Count Negative Numbers in a Sorted Matrix](https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix) — Easy
160. [Determine Whether Matrix Can Be Obtained By Rotation](https://leetcode.com/problems/determine-whether-matrix-can-be-obtained-by-rotation) — Easy
161. [Flip Square Submatrix Vertically](https://leetcode.com/problems/flip-square-submatrix-vertically) — Easy
162. [Special Positions in a Binary Matrix](https://leetcode.com/problems/special-positions-in-a-binary-matrix) — Easy
163. [Toeplitz Matrix](https://leetcode.com/problems/toeplitz-matrix) — Easy
164. [Search a 2D Matrix](https://leetcode.com/problems/search-a-2d-matrix) — Medium
165. [Set Matrix Zeroes](https://leetcode.com/problems/set-matrix-zeroes) — Medium
166. [Valid Sudoku](https://leetcode.com/problems/valid-sudoku) — Medium
167. [Maximum Side Length of a Square with Sum Less than or Equal to Threshold](https://leetcode.com/problems/maximum-side-length-of-a-square-with-sum-less-than-or-equal-to-threshold) — Medium
168. [Minimum Absolute Difference in Sliding Submatrix](https://leetcode.com/problems/minimum-absolute-difference-in-sliding-submatrix) — Medium
169. [Rotating the Box](https://leetcode.com/problems/rotating-the-box) — Medium
170. [Count Submatrices with Top-Left Element and Sum Less Than k](https://leetcode.com/problems/count-submatrices-with-top-left-element-and-sum-less-than-k) — Medium
171. [Largest Magic Square](https://leetcode.com/problems/largest-magic-square) — Medium
172. [Matrix Block Sum](https://leetcode.com/problems/matrix-block-sum) — Medium

## Stack & Queue

173. [Valid Parentheses](https://leetcode.com/problems/valid-parentheses) — Easy
174. [First Unique Character in a String](https://leetcode.com/problems/first-unique-character-in-a-string) — Easy
175. [Next Greater Element I](https://leetcode.com/problems/next-greater-element-i) — Easy
176. [Remove All Adjacent Duplicates In String](https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string) — Easy
177. [Remove Outermost Parentheses](https://leetcode.com/problems/remove-outermost-parentheses) — Easy
178. [Final Prices With a Special Discount in a Shop](https://leetcode.com/problems/final-prices-with-a-special-discount-in-a-shop) — Easy
179. [Make The String Great](https://leetcode.com/problems/make-the-string-great) — Easy
180. [Maximum Nesting Depth of the Parentheses](https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses) — Easy
181. [Next Greater Element II](https://leetcode.com/problems/next-greater-element-ii) — Medium
182. [Daily Temperatures](https://leetcode.com/problems/daily-temperatures) — Medium
183. [Simplify Path](https://leetcode.com/problems/simplify-path) — Medium
184. [Car Fleet](https://leetcode.com/problems/car-fleet) — Medium
185. [Exclusive Time of Functions](https://leetcode.com/problems/exclusive-time-of-functions) — Medium
186. [Maximum Width Ramp](https://leetcode.com/problems/maximum-width-ramp) — Medium
187. [Remove All Adjacent Duplicates in String II](https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string-ii) — Medium
188. [Score of Parentheses](https://leetcode.com/problems/score-of-parentheses) — Medium
189. [Sum of Subarray Ranges](https://leetcode.com/problems/sum-of-subarray-ranges) — Medium
190. [Largest Rectangle in Histogram](https://leetcode.com/problems/largest-rectangle-in-histogram) — Hard
191. [Number of Visible People in a Queue](https://leetcode.com/problems/number-of-visible-people-in-a-queue) — Hard

## Linked List

192. [Remove Duplicates from Sorted List](https://leetcode.com/problems/remove-duplicates-from-sorted-list) — Easy
193. [Middle of the Linked List](https://leetcode.com/problems/middle-of-the-linked-list) — Easy
194. [Linked List Cycle](https://leetcode.com/problems/linked-list-cycle) — Easy
195. [Intersection of Two Linked Lists](https://leetcode.com/problems/intersection-of-two-linked-lists) — Easy
196. [Remove Nth Node From End of List](https://leetcode.com/problems/remove-nth-node-from-end-of-list) — Medium
197. [Rotate List](https://leetcode.com/problems/rotate-list) — Medium
198. [Odd Even Linked List](https://leetcode.com/problems/odd-even-linked-list) — Medium
199. [Reverse Linked List II](https://leetcode.com/problems/reverse-linked-list-ii) — Medium
200. [Copy List with Random Pointer](https://leetcode.com/problems/copy-list-with-random-pointer) — Medium
201. [Delete Node in a Linked List](https://leetcode.com/problems/delete-node-in-a-linked-list) — Medium
202. [Delete the Middle Node of a Linked List](https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list) — Medium
203. [Linked List Cycle II](https://leetcode.com/problems/linked-list-cycle-ii) — Medium
204. [Partition List](https://leetcode.com/problems/partition-list) — Medium
205. [Remove Duplicates from Sorted List II](https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii) — Medium
206. [Find the Minimum and Maximum Number of Nodes Between Critical Points](https://leetcode.com/problems/find-the-minimum-and-maximum-number-of-nodes-between-critical-points) — Medium
207. [Reverse Nodes in Even Length Groups](https://leetcode.com/problems/reverse-nodes-in-even-length-groups) — Medium

## Trees

208. [Search in a Binary Search Tree](https://leetcode.com/problems/search-in-a-binary-search-tree) — Easy
209. [Delete Node in a BST](https://leetcode.com/problems/delete-node-in-a-bst) — Medium
210. [Insert into a Binary Search Tree](https://leetcode.com/problems/insert-into-a-binary-search-tree) — Medium
211. [Construct Binary Search Tree from Preorder Traversal](https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal) — Medium
212. [Create Binary Tree From Descriptions](https://leetcode.com/problems/create-binary-tree-from-descriptions) — Medium

## Tree Traversal

213. [Same Tree](https://leetcode.com/problems/same-tree) — Easy
214. [Binary Tree Inorder Traversal](https://leetcode.com/problems/binary-tree-inorder-traversal) — Easy
215. [Balanced Binary Tree](https://leetcode.com/problems/balanced-binary-tree) — Easy
216. [Flood Fill](https://leetcode.com/problems/flood-fill) — Easy
217. [Maximum Depth of Binary Tree](https://leetcode.com/problems/maximum-depth-of-binary-tree) — Easy
218. [Invert Binary Tree](https://leetcode.com/problems/invert-binary-tree) — Easy
219. [Symmetric Tree](https://leetcode.com/problems/symmetric-tree) — Easy
220. [Diameter of Binary Tree](https://leetcode.com/problems/diameter-of-binary-tree) — Easy
221. [Subtree of Another Tree](https://leetcode.com/problems/subtree-of-another-tree) — Easy
222. [Two Sum IV - Input is a BST](https://leetcode.com/problems/two-sum-iv-input-is-a-bst) — Easy
223. [Binary Tree Preorder Traversal](https://leetcode.com/problems/binary-tree-preorder-traversal) — Easy
224. [Path Sum](https://leetcode.com/problems/path-sum) — Easy
225. [Sum of Root To Leaf Binary Numbers](https://leetcode.com/problems/sum-of-root-to-leaf-binary-numbers) — Easy
226. [Find Mode in Binary Search Tree](https://leetcode.com/problems/find-mode-in-binary-search-tree) — Easy
227. [Island Perimeter](https://leetcode.com/problems/island-perimeter) — Easy
228. [Minimum Absolute Difference in BST](https://leetcode.com/problems/minimum-absolute-difference-in-bst) — Easy
229. [Sum of Left Leaves](https://leetcode.com/problems/sum-of-left-leaves) — Easy
230. [Binary Tree Level Order Traversal](https://leetcode.com/problems/binary-tree-level-order-traversal) — Medium
231. [Rotting Oranges](https://leetcode.com/problems/rotting-oranges) — Medium
232. [Binary Tree Zigzag Level Order Traversal](https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal) — Medium
233. [Lowest Common Ancestor of a Binary Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree) — Medium
234. [Path Sum III](https://leetcode.com/problems/path-sum-iii) — Medium
235. [Maximum Level Sum of a Binary Tree](https://leetcode.com/problems/maximum-level-sum-of-a-binary-tree) — Medium
236. [Maximum Product of Splitted Binary Tree](https://leetcode.com/problems/maximum-product-of-splitted-binary-tree) — Medium
237. [Maximum Width of Binary Tree](https://leetcode.com/problems/maximum-width-of-binary-tree) — Medium
238. [Pacific Atlantic Water Flow](https://leetcode.com/problems/pacific-atlantic-water-flow) — Medium
239. [Validate Binary Search Tree](https://leetcode.com/problems/validate-binary-search-tree) — Medium
240. [Binary Tree Right Side View](https://leetcode.com/problems/binary-tree-right-side-view) — Medium
241. [Recover Binary Search Tree](https://leetcode.com/problems/recover-binary-search-tree) — Medium
242. [Kth Smallest Element in a BST](https://leetcode.com/problems/kth-smallest-element-in-a-bst) — Medium
243. [Lowest Common Ancestor of a Binary Search Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree) — Medium
244. [Delete Nodes And Return Forest](https://leetcode.com/problems/delete-nodes-and-return-forest) — Medium
245. [Flatten a Multilevel Doubly Linked List](https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list) — Medium
246. [All Nodes Distance K in Binary Tree](https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree) — Medium
247. [Binary Tree Level Order Traversal II](https://leetcode.com/problems/binary-tree-level-order-traversal-ii) — Medium
248. [Coloring A Border](https://leetcode.com/problems/coloring-a-border) — Medium
249. [Count Good Nodes in Binary Tree](https://leetcode.com/problems/count-good-nodes-in-binary-tree) — Medium
250. [Minimum Genetic Mutation](https://leetcode.com/problems/minimum-genetic-mutation) — Medium
251. [Nearest Exit from Entrance in Maze](https://leetcode.com/problems/nearest-exit-from-entrance-in-maze) — Medium
252. [Populating Next Right Pointers in Each Node](https://leetcode.com/problems/populating-next-right-pointers-in-each-node) — Medium
253. [Shortest Bridge](https://leetcode.com/problems/shortest-bridge) — Medium
254. [Shortest Path in Binary Matrix](https://leetcode.com/problems/shortest-path-in-binary-matrix) — Medium
255. [Smallest Subtree with all the Deepest Nodes](https://leetcode.com/problems/smallest-subtree-with-all-the-deepest-nodes) — Medium
256. [Snakes and Ladders](https://leetcode.com/problems/snakes-and-ladders) — Medium
257. [Sum Root to Leaf Numbers](https://leetcode.com/problems/sum-root-to-leaf-numbers) — Medium
258. [Time Needed to Inform All Employees](https://leetcode.com/problems/time-needed-to-inform-all-employees) — Medium
259. [Trim a Binary Search Tree](https://leetcode.com/problems/trim-a-binary-search-tree) — Medium
260. [Word Ladder](https://leetcode.com/problems/word-ladder) — Hard
261. [Bus Routes](https://leetcode.com/problems/bus-routes) — Hard
262. [Jump Game IV](https://leetcode.com/problems/jump-game-iv) — Hard

## Heap / Priority Queue

263. [Relative Ranks](https://leetcode.com/problems/relative-ranks) — Easy
264. [Find K Closest Elements](https://leetcode.com/problems/find-k-closest-elements) — Medium
265. [Find K Pairs with Smallest Sums](https://leetcode.com/problems/find-k-pairs-with-smallest-sums) — Medium
266. [Single-Threaded CPU](https://leetcode.com/problems/single-threaded-cpu) — Medium
267. [Sort Characters By Frequency](https://leetcode.com/problems/sort-characters-by-frequency) — Medium
268. [Sliding Window Maximum](https://leetcode.com/problems/sliding-window-maximum) — Hard
269. [Trapping Rain Water II](https://leetcode.com/problems/trapping-rain-water-ii) — Hard
270. [Max Sum of Rectangle No Larger Than K](https://leetcode.com/problems/max-sum-of-rectangle-no-larger-than-k) — Hard
271. [Shortest Subarray with Sum at Least K](https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k) — Hard

## Recursion & Divide

272. [Majority Element](https://leetcode.com/problems/majority-element) — Easy
273. [Merge Two Sorted Lists](https://leetcode.com/problems/merge-two-sorted-lists) — Easy
274. [Reverse Linked List](https://leetcode.com/problems/reverse-linked-list) — Easy
275. [Palindrome Linked List](https://leetcode.com/problems/palindrome-linked-list) — Easy
276. [Convert Sorted Array to Binary Search Tree](https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree) — Easy
277. [Top K Frequent Elements](https://leetcode.com/problems/top-k-frequent-elements) — Medium
278. [Kth Largest Element in an Array](https://leetcode.com/problems/kth-largest-element-in-an-array) — Medium
279. [Decode String](https://leetcode.com/problems/decode-string) — Medium
280. [Sort an Array](https://leetcode.com/problems/sort-an-array) — Medium
281. [Search a 2D Matrix II](https://leetcode.com/problems/search-a-2d-matrix-ii) — Medium
282. [Swap Nodes in Pairs](https://leetcode.com/problems/swap-nodes-in-pairs) — Medium
283. [Reorder List](https://leetcode.com/problems/reorder-list) — Medium
284. [Construct Binary Tree from Preorder and Inorder Traversal](https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal) — Medium
285. [Convert Sorted List to Binary Search Tree](https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree) — Medium
286. [Sort List](https://leetcode.com/problems/sort-list) — Medium
287. [Construct Quad Tree](https://leetcode.com/problems/construct-quad-tree) — Medium
288. [Longest Substring with At Least K Repeating Characters](https://leetcode.com/problems/longest-substring-with-at-least-k-repeating-characters) — Medium
289. [Median of Two Sorted Arrays](https://leetcode.com/problems/median-of-two-sorted-arrays) — Hard
290. [Reverse Nodes in k-Group](https://leetcode.com/problems/reverse-nodes-in-k-group) — Hard
291. [Special Binary String](https://leetcode.com/problems/special-binary-string) — Hard
292. [Merge k Sorted Lists](https://leetcode.com/problems/merge-k-sorted-lists) — Hard

## Backtracking

293. [Divide an Array Into Subarrays With Minimum Cost I](https://leetcode.com/problems/divide-an-array-into-subarrays-with-minimum-cost-i) — Easy
294. [Binary Tree Paths](https://leetcode.com/problems/binary-tree-paths) — Easy
295. [Finding 3-Digit Even Numbers](https://leetcode.com/problems/finding-3-digit-even-numbers) — Easy
296. [Permutations](https://leetcode.com/problems/permutations) — Medium
297. [Letter Combinations of a Phone Number](https://leetcode.com/problems/letter-combinations-of-a-phone-number) — Medium
298. [Combination Sum](https://leetcode.com/problems/combination-sum) — Medium
299. [Combinations](https://leetcode.com/problems/combinations) — Medium
300. [Permutations II](https://leetcode.com/problems/permutations-ii) — Medium
301. [The k-th Lexicographical String of All Happy Strings of Length n](https://leetcode.com/problems/the-k-th-lexicographical-string-of-all-happy-strings-of-length-n) — Medium
302. [Word Search](https://leetcode.com/problems/word-search) — Medium
303. [Combination Sum II](https://leetcode.com/problems/combination-sum-ii) — Medium
304. [Maximum Square Area by Removing Fences From a Field](https://leetcode.com/problems/maximum-square-area-by-removing-fences-from-a-field) — Medium
305. [Equal Sum Grid Partition I](https://leetcode.com/problems/equal-sum-grid-partition-i) — Medium
306. [Path Sum II](https://leetcode.com/problems/path-sum-ii) — Medium
307. [Combination Sum III](https://leetcode.com/problems/combination-sum-iii) — Medium
308. [Longest Balanced Substring I](https://leetcode.com/problems/longest-balanced-substring-i) — Medium
309. [N-Queens](https://leetcode.com/problems/n-queens) — Hard
310. [Sudoku Solver](https://leetcode.com/problems/sudoku-solver) — Hard
311. [Word Ladder II](https://leetcode.com/problems/word-ladder-ii) — Hard
312. [Equal Sum Grid Partition II](https://leetcode.com/problems/equal-sum-grid-partition-ii) — Hard

## Greedy

313. [Assign Cookies](https://leetcode.com/problems/assign-cookies) — Easy
314. [Valid Palindrome II](https://leetcode.com/problems/valid-palindrome-ii) — Easy
315. [Array Partition](https://leetcode.com/problems/array-partition) — Easy
316. [Can Place Flowers](https://leetcode.com/problems/can-place-flowers) — Easy
317. [Earliest Finish Time for Land and Water Rides I](https://leetcode.com/problems/earliest-finish-time-for-land-and-water-rides-i) — Easy
318. [Longest Palindrome](https://leetcode.com/problems/longest-palindrome) — Easy
319. [Lemonade Change](https://leetcode.com/problems/lemonade-change) — Easy
320. [Two Furthest Houses With Different Colors](https://leetcode.com/problems/two-furthest-houses-with-different-colors) — Easy
321. [Container With Most Water](https://leetcode.com/problems/container-with-most-water) — Medium
322. [Meeting Rooms II](https://leetcode.com/problems/meeting-rooms-ii) — Medium
323. [Largest Number](https://leetcode.com/problems/largest-number) — Medium
324. [Frequency of the Most Frequent Element](https://leetcode.com/problems/frequency-of-the-most-frequent-element) — Medium
325. [Task Scheduler](https://leetcode.com/problems/task-scheduler) — Medium
326. [Earliest Finish Time for Land and Water Rides II](https://leetcode.com/problems/earliest-finish-time-for-land-and-water-rides-ii) — Medium
327. [Reorganize String](https://leetcode.com/problems/reorganize-string) — Medium
328. [Maximum Matrix Sum](https://leetcode.com/problems/maximum-matrix-sum) — Medium
329. [Divide Array in Sets of K Consecutive Numbers](https://leetcode.com/problems/divide-array-in-sets-of-k-consecutive-numbers) — Medium
330. [Gas Station](https://leetcode.com/problems/gas-station) — Medium
331. [Largest Submatrix With Rearrangements](https://leetcode.com/problems/largest-submatrix-with-rearrangements) — Medium
332. [Minimize Maximum Pair Sum in Array](https://leetcode.com/problems/minimize-maximum-pair-sum-in-array) — Medium
333. [Minimum Number of Arrows to Burst Balloons](https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons) — Medium
334. [Remove K Digits](https://leetcode.com/problems/remove-k-digits) — Medium
335. [Shortest Unsorted Continuous Subarray](https://leetcode.com/problems/shortest-unsorted-continuous-subarray) — Medium
336. [Boats to Save People](https://leetcode.com/problems/boats-to-save-people) — Medium
337. [Minimum Add to Make Parentheses Valid](https://leetcode.com/problems/minimum-add-to-make-parentheses-valid) — Medium
338. [Partitioning Into Minimum Number Of Deci-Binary Numbers](https://leetcode.com/problems/partitioning-into-minimum-number-of-deci-binary-numbers) — Medium
339. [Destroying Asteroids](https://leetcode.com/problems/destroying-asteroids) — Medium
340. [Increasing Triplet Subsequence](https://leetcode.com/problems/increasing-triplet-subsequence) — Medium
341. [Max Increase to Keep City Skyline](https://leetcode.com/problems/max-increase-to-keep-city-skyline) — Medium
342. [Maximum Ice Cream Bars](https://leetcode.com/problems/maximum-ice-cream-bars) — Medium
343. [Maximum Sum Obtained of Any Permutation](https://leetcode.com/problems/maximum-sum-obtained-of-any-permutation) — Medium
344. [Maximum Total Subarray Value I](https://leetcode.com/problems/maximum-total-subarray-value-i) — Medium
345. [Minimum Processing Time](https://leetcode.com/problems/minimum-processing-time) — Medium
346. [Remove Duplicate Letters](https://leetcode.com/problems/remove-duplicate-letters) — Medium
347. [Candy](https://leetcode.com/problems/candy) — Hard
348. [Lexicographically Smallest Generated String](https://leetcode.com/problems/lexicographically-smallest-generated-string) — Hard
349. [Minimum Initial Energy to Finish Tasks](https://leetcode.com/problems/minimum-initial-energy-to-finish-tasks) — Hard

## Graphs

350. [Find if Path Exists in Graph](https://leetcode.com/problems/find-if-path-exists-in-graph) — Easy
351. [Longest Consecutive Sequence](https://leetcode.com/problems/longest-consecutive-sequence) — Medium
352. [Number of Islands](https://leetcode.com/problems/number-of-islands) — Medium
353. [Course Schedule](https://leetcode.com/problems/course-schedule) — Medium
354. [Network Delay Time](https://leetcode.com/problems/network-delay-time) — Medium
355. [Surrounded Regions](https://leetcode.com/problems/surrounded-regions) — Medium
356. [Number of Provinces](https://leetcode.com/problems/number-of-provinces) — Medium
357. [The Earliest Moment When Everyone Become Friends](https://leetcode.com/problems/the-earliest-moment-when-everyone-become-friends) — Medium
358. [Apply Substitutions](https://leetcode.com/problems/apply-substitutions) — Medium
359. [Clone Graph](https://leetcode.com/problems/clone-graph) — Medium
360. [Course Schedule II](https://leetcode.com/problems/course-schedule-ii) — Medium
361. [Evaluate Division](https://leetcode.com/problems/evaluate-division) — Medium
362. [Minimize Hamming Distance After Swap Operations](https://leetcode.com/problems/minimize-hamming-distance-after-swap-operations) — Medium
363. [Sequence Reconstruction](https://leetcode.com/problems/sequence-reconstruction) — Medium
364. [Accounts Merge](https://leetcode.com/problems/accounts-merge) — Medium
365. [Min Cost to Connect All Points](https://leetcode.com/problems/min-cost-to-connect-all-points) — Medium
366. [Most Stones Removed with Same Row or Column](https://leetcode.com/problems/most-stones-removed-with-same-row-or-column) — Medium
367. [Detect Cycles in 2D Grid](https://leetcode.com/problems/detect-cycles-in-2d-grid) — Medium
368. [Find All Possible Recipes from Given Supplies](https://leetcode.com/problems/find-all-possible-recipes-from-given-supplies) — Medium
369. [Max Area of Island](https://leetcode.com/problems/max-area-of-island) — Medium
370. [Minimum Cost to Convert String I](https://leetcode.com/problems/minimum-cost-to-convert-string-i) — Medium
371. [Check if There is a Valid Path in a Grid](https://leetcode.com/problems/check-if-there-is-a-valid-path-in-a-grid) — Medium
372. [Find Eventual Safe States](https://leetcode.com/problems/find-eventual-safe-states) — Medium
373. [Minimum Number of Vertices to Reach All Nodes](https://leetcode.com/problems/minimum-number-of-vertices-to-reach-all-nodes) — Medium
374. [Number of Closed Islands](https://leetcode.com/problems/number-of-closed-islands) — Medium
375. [Path With Minimum Effort](https://leetcode.com/problems/path-with-minimum-effort) — Medium
376. [Path with Maximum Probability](https://leetcode.com/problems/path-with-maximum-probability) — Medium
377. [Shortest Path with Alternating Colors](https://leetcode.com/problems/shortest-path-with-alternating-colors) — Medium
378. [Swim in Rising Water](https://leetcode.com/problems/swim-in-rising-water) — Hard
379. [Last Day Where You Can Still Cross](https://leetcode.com/problems/last-day-where-you-can-still-cross) — Hard
380. [Alien Dictionary](https://leetcode.com/problems/alien-dictionary) — Hard
381. [Maximize Spanning Tree Stability with Upgrades](https://leetcode.com/problems/maximize-spanning-tree-stability-with-upgrades) — Hard
382. [Number of Islands II](https://leetcode.com/problems/number-of-islands-ii) — Hard
383. [Critical Connections in a Network](https://leetcode.com/problems/critical-connections-in-a-network) — Hard
384. [Find All People With Secret](https://leetcode.com/problems/find-all-people-with-secret) — Hard
385. [Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree](https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree) — Hard
386. [Making A Large Island](https://leetcode.com/problems/making-a-large-island) — Hard
387. [Maximum Partition Factor](https://leetcode.com/problems/maximum-partition-factor) — Hard

## Dynamic Programming

388. [Best Time to Buy and Sell Stock](https://leetcode.com/problems/best-time-to-buy-and-sell-stock) — Easy
389. [Pascal's Triangle](https://leetcode.com/problems/pascals-triangle) — Easy
390. [Min Cost Climbing Stairs](https://leetcode.com/problems/min-cost-climbing-stairs) — Easy
391. [Is Subsequence](https://leetcode.com/problems/is-subsequence) — Easy
392. [Pascal's Triangle II](https://leetcode.com/problems/pascals-triangle-ii) — Easy
393. [Longest Palindromic Substring](https://leetcode.com/problems/longest-palindromic-substring) — Medium
394. [Maximum Subarray](https://leetcode.com/problems/maximum-subarray) — Medium
395. [House Robber](https://leetcode.com/problems/house-robber) — Medium
396. [Generate Parentheses](https://leetcode.com/problems/generate-parentheses) — Medium
397. [Jump Game](https://leetcode.com/problems/jump-game) — Medium
398. [Longest Increasing Subsequence](https://leetcode.com/problems/longest-increasing-subsequence) — Medium
399. [Coin Change](https://leetcode.com/problems/coin-change) — Medium
400. [Edit Distance](https://leetcode.com/problems/edit-distance) — Medium
401. [Maximum Product Subarray](https://leetcode.com/problems/maximum-product-subarray) — Medium
402. [Jump Game II](https://leetcode.com/problems/jump-game-ii) — Medium
403. [Best Time to Buy and Sell Stock II](https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii) — Medium
404. [Champagne Tower](https://leetcode.com/problems/champagne-tower) — Medium
405. [Maximal Square](https://leetcode.com/problems/maximal-square) — Medium
406. [Cheapest Flights Within K Stops](https://leetcode.com/problems/cheapest-flights-within-k-stops) — Medium
407. [Palindrome Partitioning](https://leetcode.com/problems/palindrome-partitioning) — Medium
408. [Partition Equal Subset Sum](https://leetcode.com/problems/partition-equal-subset-sum) — Medium
409. [Sum of Subarray Minimums](https://leetcode.com/problems/sum-of-subarray-minimums) — Medium
410. [Coin Change II](https://leetcode.com/problems/coin-change-ii) — Medium
411. [Target Sum](https://leetcode.com/problems/target-sum) — Medium
412. [Maximum Path Score in a Grid](https://leetcode.com/problems/maximum-path-score-in-a-grid) — Medium
413. [Best Time to Buy and Sell Stock with Transaction Fee](https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee) — Medium
414. [House Robber II](https://leetcode.com/problems/house-robber-ii) — Medium
415. [Longest Common Subsequence](https://leetcode.com/problems/longest-common-subsequence) — Medium
416. [Longest Non-Decreasing Subarray After Replacing at Most One Element](https://leetcode.com/problems/longest-non-decreasing-subarray-after-replacing-at-most-one-element) — Medium
417. [Triangle](https://leetcode.com/problems/triangle) — Medium
418. [Unique Binary Search Trees II](https://leetcode.com/problems/unique-binary-search-trees-ii) — Medium
419. [Valid Parenthesis String](https://leetcode.com/problems/valid-parenthesis-string) — Medium
420. [01 Matrix](https://leetcode.com/problems/01-matrix) — Medium
421. [Count Square Submatrices with All Ones](https://leetcode.com/problems/count-square-submatrices-with-all-ones) — Medium
422. [Find All Possible Stable Binary Arrays I](https://leetcode.com/problems/find-all-possible-stable-binary-arrays-i) — Medium
423. [House Robber III](https://leetcode.com/problems/house-robber-iii) — Medium
424. [Interleaving String](https://leetcode.com/problems/interleaving-string) — Medium
425. [Jump Game IX](https://leetcode.com/problems/jump-game-ix) — Medium
426. [Last Stone Weight II](https://leetcode.com/problems/last-stone-weight-ii) — Medium
427. [Minimum Deletions to Make String Balanced](https://leetcode.com/problems/minimum-deletions-to-make-string-balanced) — Medium
428. [Minimum Falling Path Sum](https://leetcode.com/problems/minimum-falling-path-sum) — Medium
429. [Partition Array for Maximum Sum](https://leetcode.com/problems/partition-array-for-maximum-sum) — Medium
430. [Arithmetic Slices](https://leetcode.com/problems/arithmetic-slices) — Medium
431. [Combination Sum IV](https://leetcode.com/problems/combination-sum-iv) — Medium
432. [Decode Ways](https://leetcode.com/problems/decode-ways) — Medium
433. [Inverse Coin Change](https://leetcode.com/problems/inverse-coin-change) — Medium
434. [Longest Palindromic Subsequence](https://leetcode.com/problems/longest-palindromic-subsequence) — Medium
435. [Longest String Chain](https://leetcode.com/problems/longest-string-chain) — Medium
436. [Maximum Sum Circular Subarray](https://leetcode.com/problems/maximum-sum-circular-subarray) — Medium
437. [Minimum Path Sum](https://leetcode.com/problems/minimum-path-sum) — Medium
438. [Non-overlapping Intervals](https://leetcode.com/problems/non-overlapping-intervals) — Medium
439. [Number of Ways to Arrive at Destination](https://leetcode.com/problems/number-of-ways-to-arrive-at-destination) — Medium
440. [Best Time to Buy and Sell Stock with Cooldown](https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown) — Medium
441. [Longest Arithmetic Subsequence](https://leetcode.com/problems/longest-arithmetic-subsequence) — Medium
442. [Longest Turbulent Subarray](https://leetcode.com/problems/longest-turbulent-subarray) — Medium
443. [Minimum Cost For Tickets](https://leetcode.com/problems/minimum-cost-for-tickets) — Medium
444. [Minimum Number of Flips to Make the Binary String Alternating](https://leetcode.com/problems/minimum-number-of-flips-to-make-the-binary-string-alternating) — Medium
445. [Solving Questions With Brainpower](https://leetcode.com/problems/solving-questions-with-brainpower) — Medium
446. [Unique Paths II](https://leetcode.com/problems/unique-paths-ii) — Medium
447. [Trapping Rain Water](https://leetcode.com/problems/trapping-rain-water) — Hard
448. [Split Array Largest Sum](https://leetcode.com/problems/split-array-largest-sum) — Hard
449. [Regular Expression Matching](https://leetcode.com/problems/regular-expression-matching) — Hard
450. [Maximal Rectangle](https://leetcode.com/problems/maximal-rectangle) — Hard
451. [Russian Doll Envelopes](https://leetcode.com/problems/russian-doll-envelopes) — Hard
452. [Longest Valid Parentheses](https://leetcode.com/problems/longest-valid-parentheses) — Hard
453. [Binary Tree Maximum Path Sum](https://leetcode.com/problems/binary-tree-maximum-path-sum) — Hard
454. [Longest Increasing Path in a Matrix](https://leetcode.com/problems/longest-increasing-path-in-a-matrix) — Hard
455. [Wildcard Matching](https://leetcode.com/problems/wildcard-matching) — Hard
456. [Maximum Score From Grid Operations](https://leetcode.com/problems/maximum-score-from-grid-operations) — Hard
457. [Number of ZigZag Arrays I](https://leetcode.com/problems/number-of-zigzag-arrays-i) — Hard
458. [Burst Balloons](https://leetcode.com/problems/burst-balloons) — Hard
459. [Minimum Cost Path with Teleportations](https://leetcode.com/problems/minimum-cost-path-with-teleportations) — Hard
460. [Minimum Time to Finish the Race](https://leetcode.com/problems/minimum-time-to-finish-the-race) — Hard
461. [Sum of Distances in Tree](https://leetcode.com/problems/sum-of-distances-in-tree) — Hard
462. [Tallest Billboard](https://leetcode.com/problems/tallest-billboard) — Hard
463. [Cherry Pickup](https://leetcode.com/problems/cherry-pickup) — Hard
464. [Jump Game V](https://leetcode.com/problems/jump-game-v) — Hard
465. [Max Dot Product of Two Subsequences](https://leetcode.com/problems/max-dot-product-of-two-subsequences) — Hard
466. [Maximize Cyclic Partition Score](https://leetcode.com/problems/maximize-cyclic-partition-score) — Hard
467. [Maximum Profit in Job Scheduling](https://leetcode.com/problems/maximum-profit-in-job-scheduling) — Hard
468. [Maximum Sum BST in Binary Tree](https://leetcode.com/problems/maximum-sum-bst-in-binary-tree) — Hard
469. [Minimum Distance to Type a Word Using Two Fingers](https://leetcode.com/problems/minimum-distance-to-type-a-word-using-two-fingers) — Hard
470. [Palindrome Partitioning II](https://leetcode.com/problems/palindrome-partitioning-ii) — Hard
471. [Remove Boxes](https://leetcode.com/problems/remove-boxes) — Hard
472. [Trionic Array II](https://leetcode.com/problems/trionic-array-ii) — Hard
473. [Frog Jump](https://leetcode.com/problems/frog-jump) — Hard
474. [Minimum Cost to Cut a Stick](https://leetcode.com/problems/minimum-cost-to-cut-a-stick) — Hard
475. [Odd Even Jump](https://leetcode.com/problems/odd-even-jump) — Hard
476. [Race Car](https://leetcode.com/problems/race-car) — Hard
477. [Scramble String](https://leetcode.com/problems/scramble-string) — Hard

## Bit Manipulation

478. [Single Number](https://leetcode.com/problems/single-number) — Easy
479. [Set Mismatch](https://leetcode.com/problems/set-mismatch) — Easy
480. [Reverse Bits](https://leetcode.com/problems/reverse-bits) — Easy
481. [Number of 1 Bits](https://leetcode.com/problems/number-of-1-bits) — Easy
482. [Binary Gap](https://leetcode.com/problems/binary-gap) — Easy
483. [Binary Number with Alternating Bits](https://leetcode.com/problems/binary-number-with-alternating-bits) — Easy
484. [Complement of Base 10 Integer](https://leetcode.com/problems/complement-of-base-10-integer) — Easy
485. [Hamming Distance](https://leetcode.com/problems/hamming-distance) — Easy
486. [Sort Integers by The Number of 1 Bits](https://leetcode.com/problems/sort-integers-by-the-number-of-1-bits) — Easy
487. [Binary Watch](https://leetcode.com/problems/binary-watch) — Easy
488. [Construct the Minimum Bitwise Array I](https://leetcode.com/problems/construct-the-minimum-bitwise-array-i) — Easy
489. [Count Complete Tree Nodes](https://leetcode.com/problems/count-complete-tree-nodes) — Easy
490. [Find the Difference](https://leetcode.com/problems/find-the-difference) — Easy
491. [First Letter to Appear Twice](https://leetcode.com/problems/first-letter-to-appear-twice) — Easy
492. [Subsets](https://leetcode.com/problems/subsets) — Medium
493. [Subsets II](https://leetcode.com/problems/subsets-ii) — Medium
494. [Find the Duplicate Number](https://leetcode.com/problems/find-the-duplicate-number) — Medium
495. [Find the Prefix Common Array of Two Arrays](https://leetcode.com/problems/find-the-prefix-common-array-of-two-arrays) — Medium
496. [Single Number II](https://leetcode.com/problems/single-number-ii) — Medium
497. [Check If a String Contains All Binary Codes of Size K](https://leetcode.com/problems/check-if-a-string-contains-all-binary-codes-of-size-k) — Medium
498. [Pyramid Transition Matrix](https://leetcode.com/problems/pyramid-transition-matrix) — Medium
499. [Number of Wonderful Substrings](https://leetcode.com/problems/number-of-wonderful-substrings) — Medium
500. [Partition to K Equal Sum Subsets](https://leetcode.com/problems/partition-to-k-equal-sum-subsets) — Medium
501. [Repeated DNA Sequences](https://leetcode.com/problems/repeated-dna-sequences) — Medium
502. [Single Number III](https://leetcode.com/problems/single-number-iii) — Medium
503. [Partition Array Into Two Arrays to Minimize Sum Difference](https://leetcode.com/problems/partition-array-into-two-arrays-to-minimize-sum-difference) — Hard
504. [Next Special Palindrome Number](https://leetcode.com/problems/next-special-palindrome-number) — Hard
505. [Shortest Path Visiting All Nodes](https://leetcode.com/problems/shortest-path-visiting-all-nodes) — Hard
506. [Unique Paths III](https://leetcode.com/problems/unique-paths-iii) — Hard

## Math & Geometry

507. [Palindrome Number](https://leetcode.com/problems/palindrome-number) — Easy
508. [Roman to Integer](https://leetcode.com/problems/roman-to-integer) — Easy
509. [Climbing Stairs](https://leetcode.com/problems/climbing-stairs) — Easy
510. [Plus One](https://leetcode.com/problems/plus-one) — Easy
511. [Missing Number](https://leetcode.com/problems/missing-number) — Easy
512. [Sqrt(x)](https://leetcode.com/problems/sqrtx) — Easy
513. [Fibonacci Number](https://leetcode.com/problems/fibonacci-number) — Easy
514. [Power of Two](https://leetcode.com/problems/power-of-two) — Easy
515. [Add Two Integers](https://leetcode.com/problems/add-two-integers) — Easy
516. [Happy Number](https://leetcode.com/problems/happy-number) — Easy
517. [Find Missing and Repeated Values](https://leetcode.com/problems/find-missing-and-repeated-values) — Easy
518. [Excel Sheet Column Title](https://leetcode.com/problems/excel-sheet-column-title) — Easy
519. [Greatest Common Divisor of Strings](https://leetcode.com/problems/greatest-common-divisor-of-strings) — Easy
520. [N-th Tribonacci Number](https://leetcode.com/problems/n-th-tribonacci-number) — Easy
521. [Number of Good Pairs](https://leetcode.com/problems/number-of-good-pairs) — Easy
522. [Perfect Number](https://leetcode.com/problems/perfect-number) — Easy
523. [Valid Perfect Square](https://leetcode.com/problems/valid-perfect-square) — Easy
524. [Find Numbers with Even Number of Digits](https://leetcode.com/problems/find-numbers-with-even-number-of-digits) — Easy
525. [Construct Uniform Parity Array I](https://leetcode.com/problems/construct-uniform-parity-array-i) — Easy
526. [Minimum Element After Replacement With Digit Sum](https://leetcode.com/problems/minimum-element-after-replacement-with-digit-sum) — Easy
527. [Minimum Operations to Make Array Sum Divisible by K](https://leetcode.com/problems/minimum-operations-to-make-array-sum-divisible-by-k) — Easy
528. [Minimum Time Visiting All Points](https://leetcode.com/problems/minimum-time-visiting-all-points) — Easy
529. [Mirror Distance of an Integer](https://leetcode.com/problems/mirror-distance-of-an-integer) — Easy
530. [Power of Three](https://leetcode.com/problems/power-of-three) — Easy
531. [Prime Number of Set Bits in Binary Representation](https://leetcode.com/problems/prime-number-of-set-bits-in-binary-representation) — Easy
532. [Subtract the Product and Sum of Digits of an Integer](https://leetcode.com/problems/subtract-the-product-and-sum-of-digits-of-an-integer) — Easy
533. [Ugly Number](https://leetcode.com/problems/ugly-number) — Easy
534. [Base 7](https://leetcode.com/problems/base-7) — Easy
535. [Count Odd Numbers in an Interval Range](https://leetcode.com/problems/count-odd-numbers-in-an-interval-range) — Easy
536. [Count Partitions with Even Sum Difference](https://leetcode.com/problems/count-partitions-with-even-sum-difference) — Easy
537. [Count the Digits That Divide a Number](https://leetcode.com/problems/count-the-digits-that-divide-a-number) — Easy
538. [Day of the Year](https://leetcode.com/problems/day-of-the-year) — Easy
539. [Divisor Game](https://leetcode.com/problems/divisor-game) — Easy
540. [Find Greatest Common Divisor of Array](https://leetcode.com/problems/find-greatest-common-divisor-of-array) — Easy
541. [Minimum Number of Pushes to Type Word I](https://leetcode.com/problems/minimum-number-of-pushes-to-type-word-i) — Easy
542. [Smallest Even Multiple](https://leetcode.com/problems/smallest-even-multiple) — Easy
543. [X of a Kind in a Deck of Cards](https://leetcode.com/problems/x-of-a-kind-in-a-deck-of-cards) — Easy
544. [Add Two Numbers](https://leetcode.com/problems/add-two-numbers) — Medium
545. [Reverse Integer](https://leetcode.com/problems/reverse-integer) — Medium
546. [Rotate Array](https://leetcode.com/problems/rotate-array) — Medium
547. [Rotate Image](https://leetcode.com/problems/rotate-image) — Medium
548. [Pow(x, n)](https://leetcode.com/problems/powx-n) — Medium
549. [Count Primes](https://leetcode.com/problems/count-primes) — Medium
550. [Unique Paths](https://leetcode.com/problems/unique-paths) — Medium
551. [Count Good Numbers](https://leetcode.com/problems/count-good-numbers) — Medium
552. [Divide Two Integers](https://leetcode.com/problems/divide-two-integers) — Medium
553. [Integer to Roman](https://leetcode.com/problems/integer-to-roman) — Medium
554. [Random Pick with Weight](https://leetcode.com/problems/random-pick-with-weight) — Medium
555. [Evaluate Reverse Polish Notation](https://leetcode.com/problems/evaluate-reverse-polish-notation) — Medium
556. [Sum of Two Integers](https://leetcode.com/problems/sum-of-two-integers) — Medium
557. [Angle Between Hands of a Clock](https://leetcode.com/problems/angle-between-hands-of-a-clock) — Medium
558. [Basic Calculator II](https://leetcode.com/problems/basic-calculator-ii) — Medium
559. [Factorial Trailing Zeroes](https://leetcode.com/problems/factorial-trailing-zeroes) — Medium
560. [Get Biggest Three Rhombus Sums in a Grid](https://leetcode.com/problems/get-biggest-three-rhombus-sums-in-a-grid) — Medium
561. [Integer Break](https://leetcode.com/problems/integer-break) — Medium
562. [Interval List Intersections](https://leetcode.com/problems/interval-list-intersections) — Medium
563. [Largest Divisible Subset](https://leetcode.com/problems/largest-divisible-subset) — Medium
564. [Magic Squares In Grid](https://leetcode.com/problems/magic-squares-in-grid) — Medium
565. [Minimum Jumps to Reach End via Prime Teleportation](https://leetcode.com/problems/minimum-jumps-to-reach-end-via-prime-teleportation) — Medium
566. [Minimum Operations to Transform Array into Alternating Prime](https://leetcode.com/problems/minimum-operations-to-transform-array-into-alternating-prime) — Medium
567. [Perfect Squares](https://leetcode.com/problems/perfect-squares) — Medium
568. [Prime Palindrome](https://leetcode.com/problems/prime-palindrome) — Medium
569. [Rectangle Area](https://leetcode.com/problems/rectangle-area) — Medium
570. [Rotated Digits](https://leetcode.com/problems/rotated-digits) — Medium
571. [Sort Transformed Array](https://leetcode.com/problems/sort-transformed-array) — Medium
572. [Strictly Palindromic Number](https://leetcode.com/problems/strictly-palindromic-number) — Medium
573. [Add Two Numbers II](https://leetcode.com/problems/add-two-numbers-ii) — Medium
574. [Bulb Switcher](https://leetcode.com/problems/bulb-switcher) — Medium
575. [Concatenate Non-Zero Digits and Multiply by Sum II](https://leetcode.com/problems/concatenate-non-zero-digits-and-multiply-by-sum-ii) — Medium
576. [Count K-th Roots in a Range](https://leetcode.com/problems/count-k-th-roots-in-a-range) — Medium
577. [Escape The Ghosts](https://leetcode.com/problems/escape-the-ghosts) — Medium
578. [Find the Largest Area of Square Inside Two Rectangles](https://leetcode.com/problems/find-the-largest-area-of-square-inside-two-rectangles) — Medium
579. [Four Divisors](https://leetcode.com/problems/four-divisors) — Medium
580. [Fraction to Recurring Decimal](https://leetcode.com/problems/fraction-to-recurring-decimal) — Medium
581. [Linked List Random Node](https://leetcode.com/problems/linked-list-random-node) — Medium
582. [Minimum Absolute Distance Between Mirror Pairs](https://leetcode.com/problems/minimum-absolute-distance-between-mirror-pairs) — Medium
583. [Minimum Area Rectangle](https://leetcode.com/problems/minimum-area-rectangle) — Medium
584. [Minimum Area Rectangle II](https://leetcode.com/problems/minimum-area-rectangle-ii) — Medium
585. [Minimum Number of Seconds to Make Mountain Height Zero](https://leetcode.com/problems/minimum-number-of-seconds-to-make-mountain-height-zero) — Medium
586. [Nth Digit](https://leetcode.com/problems/nth-digit) — Medium
587. [Number of Pairs of Interchangeable Rectangles](https://leetcode.com/problems/number-of-pairs-of-interchangeable-rectangles) — Medium
588. [Number of Ways to Reach a Position After Exactly k Steps](https://leetcode.com/problems/number-of-ways-to-reach-a-position-after-exactly-k-steps) — Medium
589. [Rotate Function](https://leetcode.com/problems/rotate-function) — Medium
590. [Smallest Integer Divisible by K](https://leetcode.com/problems/smallest-integer-divisible-by-k) — Medium
591. [Total Waviness of Numbers in Range I](https://leetcode.com/problems/total-waviness-of-numbers-in-range-i) — Medium
592. [Unique Binary Search Trees](https://leetcode.com/problems/unique-binary-search-trees) — Medium
593. [Basic Calculator](https://leetcode.com/problems/basic-calculator) — Hard
594. [Permutation Sequence](https://leetcode.com/problems/permutation-sequence) — Hard
595. [Number of Digit One](https://leetcode.com/problems/number-of-digit-one) — Hard
596. [Number of Ways to Assign Edge Weights II](https://leetcode.com/problems/number-of-ways-to-assign-edge-weights-ii) — Hard
597. [Number of ZigZag Arrays II](https://leetcode.com/problems/number-of-zigzag-arrays-ii) — Hard
598. [Employee Free Time](https://leetcode.com/problems/employee-free-time) — Hard
599. [Max Points on a Line](https://leetcode.com/problems/max-points-on-a-line) — Hard
600. [Maximize the Distance Between Points on a Square](https://leetcode.com/problems/maximize-the-distance-between-points-on-a-square) — Hard
601. [Minimum Deletions to Make Array Divisible](https://leetcode.com/problems/minimum-deletions-to-make-array-divisible) — Hard
602. [24 Game](https://leetcode.com/problems/24-game) — Hard
603. [Basic Calculator III](https://leetcode.com/problems/basic-calculator-iii) — Hard
604. [Cat and Mouse II](https://leetcode.com/problems/cat-and-mouse-ii) — Hard
605. [Count Sequences to K](https://leetcode.com/problems/count-sequences-to-k) — Hard
606. [Expression Add Operators](https://leetcode.com/problems/expression-add-operators) — Hard
607. [Find Nth Smallest Integer With K One Bits](https://leetcode.com/problems/find-nth-smallest-integer-with-k-one-bits) — Hard
608. [Find the Number of Ways to Place People II](https://leetcode.com/problems/find-the-number-of-ways-to-place-people-ii) — Hard
609. [Total Waviness of Numbers in Range II](https://leetcode.com/problems/total-waviness-of-numbers-in-range-ii) — Hard

## Tries & Advanced

610. [Longest Common Prefix](https://leetcode.com/problems/longest-common-prefix) — Easy
611. [Subarrays Distinct Element Sum of Squares I](https://leetcode.com/problems/subarrays-distinct-element-sum-of-squares-i) — Easy
612. [Word Break](https://leetcode.com/problems/word-break) — Medium
613. [Find the Length of the Longest Common Prefix](https://leetcode.com/problems/find-the-length-of-the-longest-common-prefix) — Medium
614. [Number of Longest Increasing Subsequence](https://leetcode.com/problems/number-of-longest-increasing-subsequence) — Medium
615. [Maximum XOR of Two Numbers in an Array](https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array) — Medium
616. [Queue Reconstruction by Height](https://leetcode.com/problems/queue-reconstruction-by-height) — Medium
617. [Words Within Two Edits of Dictionary](https://leetcode.com/problems/words-within-two-edits-of-dictionary) — Medium
618. [Count Subarrays With Majority Element I](https://leetcode.com/problems/count-subarrays-with-majority-element-i) — Medium
619. [Extra Characters in a String](https://leetcode.com/problems/extra-characters-in-a-string) — Medium
620. [Lexicographical Numbers](https://leetcode.com/problems/lexicographical-numbers) — Medium
621. [Longest Balanced Subarray I](https://leetcode.com/problems/longest-balanced-subarray-i) — Medium
622. [Number of Matching Subsequences](https://leetcode.com/problems/number-of-matching-subsequences) — Medium
623. [Remove Sub-Folders from the Filesystem](https://leetcode.com/problems/remove-sub-folders-from-the-filesystem) — Medium
624. [Top K Frequent Words](https://leetcode.com/problems/top-k-frequent-words) — Medium
625. [Longest Balanced Subarray II](https://leetcode.com/problems/longest-balanced-subarray-ii) — Hard
626. [Block Placement Queries](https://leetcode.com/problems/block-placement-queries) — Hard
627. [Reverse Pairs](https://leetcode.com/problems/reverse-pairs) — Hard
628. [Longest Duplicate Substring](https://leetcode.com/problems/longest-duplicate-substring) — Hard
629. [Count of Smaller Numbers After Self](https://leetcode.com/problems/count-of-smaller-numbers-after-self) — Hard
630. [Count of Range Sum](https://leetcode.com/problems/count-of-range-sum) — Hard
631. [K-th Smallest in Lexicographical Order](https://leetcode.com/problems/k-th-smallest-in-lexicographical-order) — Hard
632. [Maximum Total Subarray Value II](https://leetcode.com/problems/maximum-total-subarray-value-ii) — Hard
633. [Palindrome Pairs](https://leetcode.com/problems/palindrome-pairs) — Hard
634. [Separate Squares II](https://leetcode.com/problems/separate-squares-ii) — Hard
635. [Word Break II](https://leetcode.com/problems/word-break-ii) — Hard
636. [Word Search II](https://leetcode.com/problems/word-search-ii) — Hard

## Design & Simulation

637. [Concatenation of Array](https://leetcode.com/problems/concatenation-of-array) — Easy
638. [Add Binary](https://leetcode.com/problems/add-binary) — Easy
639. [Logger Rate Limiter](https://leetcode.com/problems/logger-rate-limiter) — Easy
640. [Kth Largest Element in a Stream](https://leetcode.com/problems/kth-largest-element-in-a-stream) — Easy
641. [Backspace String Compare](https://leetcode.com/problems/backspace-string-compare) — Easy
642. [Fizz Buzz](https://leetcode.com/problems/fizz-buzz) — Easy
643. [Implement Queue using Stacks](https://leetcode.com/problems/implement-queue-using-stacks) — Easy
644. [Implement Stack using Queues](https://leetcode.com/problems/implement-stack-using-queues) — Easy
645. [Add Digits](https://leetcode.com/problems/add-digits) — Easy
646. [First Bad Version](https://leetcode.com/problems/first-bad-version) — Easy
647. [Design Parking System](https://leetcode.com/problems/design-parking-system) — Easy
648. [Add Strings](https://leetcode.com/problems/add-strings) — Easy
649. [Number of Recent Calls](https://leetcode.com/problems/number-of-recent-calls) — Easy
650. [Range Sum Query - Immutable](https://leetcode.com/problems/range-sum-query-immutable) — Easy
651. [Separate the Digits in an Array](https://leetcode.com/problems/separate-the-digits-in-an-array) — Easy
652. [Final Value of Variable After Performing Operations](https://leetcode.com/problems/final-value-of-variable-after-performing-operations) — Easy
653. [Number of Students Unable to Eat Lunch](https://leetcode.com/problems/number-of-students-unable-to-eat-lunch) — Easy
654. [Reshape the Matrix](https://leetcode.com/problems/reshape-the-matrix) — Easy
655. [Water Bottles](https://leetcode.com/problems/water-bottles) — Easy
656. [Build Array from Permutation](https://leetcode.com/problems/build-array-from-permutation) — Easy
657. [Convert 1D Array Into 2D Array](https://leetcode.com/problems/convert-1d-array-into-2d-array) — Easy
658. [Design HashSet](https://leetcode.com/problems/design-hashset) — Easy
659. [Guess Number Higher or Lower](https://leetcode.com/problems/guess-number-higher-or-lower) — Easy
660. [Matrix Similarity After Cyclic Shifts](https://leetcode.com/problems/matrix-similarity-after-cyclic-shifts) — Easy
661. [Minimum Pair Removal to Sort Array I](https://leetcode.com/problems/minimum-pair-removal-to-sort-array-i) — Easy
662. [Moving Average from Data Stream](https://leetcode.com/problems/moving-average-from-data-stream) — Easy
663. [Robot Return to Origin](https://leetcode.com/problems/robot-return-to-origin) — Easy
664. [Traffic Signal Color](https://leetcode.com/problems/traffic-signal-color) — Easy
665. [Transformed Array](https://leetcode.com/problems/transformed-array) — Easy
666. [Transpose Matrix](https://leetcode.com/problems/transpose-matrix) — Easy
667. [Weighted Word Mapping](https://leetcode.com/problems/weighted-word-mapping) — Easy
668. [Spiral Matrix](https://leetcode.com/problems/spiral-matrix) — Medium
669. [LRU Cache](https://leetcode.com/problems/lru-cache) — Medium
670. [Min Stack](https://leetcode.com/problems/min-stack) — Medium
671. [Insert Delete GetRandom O(1)](https://leetcode.com/problems/insert-delete-getrandom-o1) — Medium
672. [Range Sum Query 2D - Immutable](https://leetcode.com/problems/range-sum-query-2d-immutable) — Medium
673. [Rearrange Array Elements by Sign](https://leetcode.com/problems/rearrange-array-elements-by-sign) — Medium
674. [Car Pooling](https://leetcode.com/problems/car-pooling) — Medium
675. [Asteroid Collision](https://leetcode.com/problems/asteroid-collision) — Medium
676. [Online Stock Span](https://leetcode.com/problems/online-stock-span) — Medium
677. [Design Linked List](https://leetcode.com/problems/design-linked-list) — Medium
678. [Find Kth Bit in Nth Binary String](https://leetcode.com/problems/find-kth-bit-in-nth-binary-string) — Medium
679. [Implement Trie (Prefix Tree)](https://leetcode.com/problems/implement-trie-prefix-tree) — Medium
680. [Time Based Key-Value Store](https://leetcode.com/problems/time-based-key-value-store) — Medium
681. [Build an Array With Stack Operations](https://leetcode.com/problems/build-an-array-with-stack-operations) — Medium
682. [Design Circular Queue](https://leetcode.com/problems/design-circular-queue) — Medium
683. [Multiply Strings](https://leetcode.com/problems/multiply-strings) — Medium
684. [Concatenation of Consecutive Binary Numbers](https://leetcode.com/problems/concatenation-of-consecutive-binary-numbers) — Medium
685. [Design Auction System](https://leetcode.com/problems/design-auction-system) — Medium
686. [Design Hit Counter](https://leetcode.com/problems/design-hit-counter) — Medium
687. [Number of Steps to Reduce a Number in Binary Representation to One](https://leetcode.com/problems/number-of-steps-to-reduce-a-number-in-binary-representation-to-one) — Medium
688. [Binary Search Tree Iterator](https://leetcode.com/problems/binary-search-tree-iterator) — Medium
689. [Count Unhappy Friends](https://leetcode.com/problems/count-unhappy-friends) — Medium
690. [Cyclically Rotating a Grid](https://leetcode.com/problems/cyclically-rotating-a-grid) — Medium
691. [Decode the Slanted Ciphertext](https://leetcode.com/problems/decode-the-slanted-ciphertext) — Medium
692. [Design Circular Deque](https://leetcode.com/problems/design-circular-deque) — Medium
693. [Design Twitter](https://leetcode.com/problems/design-twitter) — Medium
694. [Design a Stack With Increment Operation](https://leetcode.com/problems/design-a-stack-with-increment-operation) — Medium
695. [RLE Iterator](https://leetcode.com/problems/rle-iterator) — Medium
696. [Seat Reservation Manager](https://leetcode.com/problems/seat-reservation-manager) — Medium
697. [Snapshot Array](https://leetcode.com/problems/snapshot-array) — Medium
698. [Walking Robot Simulation](https://leetcode.com/problems/walking-robot-simulation) — Medium
699. [Find Median from Data Stream](https://leetcode.com/problems/find-median-from-data-stream) — Hard
700. [Guess the Word](https://leetcode.com/problems/guess-the-word) — Hard
701. [Range Module](https://leetcode.com/problems/range-module) — Hard
702. [Text Justification](https://leetcode.com/problems/text-justification) — Hard
703. [Design Search Autocomplete System](https://leetcode.com/problems/design-search-autocomplete-system) — Hard
704. [LFU Cache](https://leetcode.com/problems/lfu-cache) — Hard
705. [Find in Mountain Array](https://leetcode.com/problems/find-in-mountain-array) — Hard
706. [Serialize and Deserialize Binary Tree](https://leetcode.com/problems/serialize-and-deserialize-binary-tree) — Hard
707. [Robot Collisions](https://leetcode.com/problems/robot-collisions) — Hard

## SQL

708. [Combine Two Tables](https://leetcode.com/problems/combine-two-tables) — Easy
709. [Recyclable and Low Fat Products](https://leetcode.com/problems/recyclable-and-low-fat-products) — Easy
710. [Employees Earning More Than Their Managers](https://leetcode.com/problems/employees-earning-more-than-their-managers) — Easy
711. [Article Views I](https://leetcode.com/problems/article-views-i) — Easy
712. [Rising Temperature](https://leetcode.com/problems/rising-temperature) — Easy
713. [Big Countries](https://leetcode.com/problems/big-countries) — Easy
714. [Customers Who Never Order](https://leetcode.com/problems/customers-who-never-order) — Easy
715. [Employee Bonus](https://leetcode.com/problems/employee-bonus) — Easy
716. [Delete Duplicate Emails](https://leetcode.com/problems/delete-duplicate-emails) — Easy
717. [Game Play Analysis I](https://leetcode.com/problems/game-play-analysis-i) — Easy
718. [Project Employees I](https://leetcode.com/problems/project-employees-i) — Easy
719. [Replace Employee ID With The Unique Identifier](https://leetcode.com/problems/replace-employee-id-with-the-unique-identifier) — Easy
720. [Customer Who Visited but Did Not Make Any Transactions](https://leetcode.com/problems/customer-who-visited-but-did-not-make-any-transactions) — Easy
721. [Duplicate Emails](https://leetcode.com/problems/duplicate-emails) — Easy
722. [Find Customer Referee](https://leetcode.com/problems/find-customer-referee) — Easy
723. [Number of Unique Subjects Taught by Each Teacher](https://leetcode.com/problems/number-of-unique-subjects-taught-by-each-teacher) — Easy
724. [User Activity for the Past 30 Days I](https://leetcode.com/problems/user-activity-for-the-past-30-days-i) — Easy
725. [Average Time of Process per Machine](https://leetcode.com/problems/average-time-of-process-per-machine) — Easy
726. [Not Boring Movies](https://leetcode.com/problems/not-boring-movies) — Easy
727. [Actors and Directors Who Cooperated At Least Three Times](https://leetcode.com/problems/actors-and-directors-who-cooperated-at-least-three-times) — Easy
728. [Average Selling Price](https://leetcode.com/problems/average-selling-price) — Easy
729. [Classes With at Least 5 Students](https://leetcode.com/problems/classes-with-at-least-5-students) — Easy
730. [Find Followers Count](https://leetcode.com/problems/find-followers-count) — Easy
731. [Fix Names in a Table](https://leetcode.com/problems/fix-names-in-a-table) — Easy
732. [Group Sold Products By The Date](https://leetcode.com/problems/group-sold-products-by-the-date) — Easy
733. [Queries Quality and Percentage](https://leetcode.com/problems/queries-quality-and-percentage) — Easy
734. [Reformat Department Table](https://leetcode.com/problems/reformat-department-table) — Easy
735. [Sales Person](https://leetcode.com/problems/sales-person) — Easy
736. [Students and Examinations](https://leetcode.com/problems/students-and-examinations) — Easy
737. [Triangle Judgement](https://leetcode.com/problems/triangle-judgement) — Easy
738. [Second Highest Salary](https://leetcode.com/problems/second-highest-salary) — Medium
739. [Managers with at Least 5 Direct Reports](https://leetcode.com/problems/managers-with-at-least-5-direct-reports) — Medium
740. [Monthly Transactions I](https://leetcode.com/problems/monthly-transactions-i) — Medium
741. [Game Play Analysis IV](https://leetcode.com/problems/game-play-analysis-iv) — Medium
742. [Nth Highest Salary](https://leetcode.com/problems/nth-highest-salary) — Medium
743. [Product Price at a Given Date](https://leetcode.com/problems/product-price-at-a-given-date) — Medium
744. [Product Sales Analysis III](https://leetcode.com/problems/product-sales-analysis-iii) — Medium
745. [Rank Scores](https://leetcode.com/problems/rank-scores) — Medium
746. [Restaurant Growth](https://leetcode.com/problems/restaurant-growth) — Medium
747. [Consecutive Numbers](https://leetcode.com/problems/consecutive-numbers) — Medium
748. [Count Salary Categories](https://leetcode.com/problems/count-salary-categories) — Medium
749. [Find COVID Recovery Patients](https://leetcode.com/problems/find-covid-recovery-patients) — Medium
750. [Investments in 2016](https://leetcode.com/problems/investments-in-2016) — Medium
751. [Market Analysis I](https://leetcode.com/problems/market-analysis-i) — Medium
752. [Movie Rating](https://leetcode.com/problems/movie-rating) — Medium
753. [Human Traffic of Stadium](https://leetcode.com/problems/human-traffic-of-stadium) — Hard
754. [Trips and Users](https://leetcode.com/problems/trips-and-users) — Hard

## Shell

755. [Tenth Line](https://leetcode.com/problems/tenth-line) — Easy
756. [Valid Phone Numbers](https://leetcode.com/problems/valid-phone-numbers) — Easy
757. [Transpose File](https://leetcode.com/problems/transpose-file) — Medium

## Misc

758. [Create Hello World Function](https://leetcode.com/problems/create-hello-world-function) — Easy
759. [Array Prototype Last](https://leetcode.com/problems/array-prototype-last) — Easy
760. [Counter](https://leetcode.com/problems/counter) — Easy
761. [Create a DataFrame from List](https://leetcode.com/problems/create-a-dataframe-from-list) — Easy
762. [Select Data](https://leetcode.com/problems/select-data) — Easy
763. [Sleep](https://leetcode.com/problems/sleep) — Easy
764. [Sort By](https://leetcode.com/problems/sort-by) — Easy
765. [Timeout Cancellation](https://leetcode.com/problems/timeout-cancellation) — Easy
766. [Convert Object to JSON String](https://leetcode.com/problems/convert-object-to-json-string) — Medium
767. [Cache With Time Limit](https://leetcode.com/problems/cache-with-time-limit) — Medium
768. [Maximum Subarray Sum After at Most K Swaps](https://leetcode.com/problems/maximum-subarray-sum-after-at-most-k-swaps) — Hard
